// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

function generateAnimatedComponent(animationCode, componentName) {
  var partial_arg = /\${componentName}/g;
  var replaceComponentName = function (param) {
    return param.replace(partial_arg, componentName);
  };
  var partial_arg$1 = /\${animationCode}/g;
  var param = Curry._1(replaceComponentName, "\n    import styled, { keyframes } from 'styled-components';\n    import BaseAnimation from '../BaseAnimation';\n\n    const ${componentName}Animation = keyframes`\n      ${animationCode}\n    `;\n\n    const ${componentName} = styled(BaseAnimation)`\n      animation-name: ${${componentName}Animation};\n    `;\n\n    export default ${componentName};\n  ");
  return param.replace(partial_arg$1, animationCode);
}

exports.generateAnimatedComponent = generateAnimatedComponent;
/* No side effect */
