// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssTree = require("css-tree");
var AnimatedComponent = require("./AnimatedComponent.bs.js");

var ast = CssTree.parse("@keyframes zoomInLeft {\n  from {\n    opacity: 0;\n    transform: scale3d(0.1, 0.1, 0.1) translate3d(-1000px, 0, 0);\n    animation-timing-function: cubic-bezier(0.55, 0.055, 0.675, 0.19);\n  }\n\n  60% {\n    opacity: 1;\n    transform: scale3d(0.475, 0.475, 0.475) translate3d(10px, 0, 0);\n    animation-timing-function: cubic-bezier(0.175, 0.885, 0.32, 1);\n  }\n}\n\n.zoomInLeft {\n  animation-name: zoomInLeft;\n}");

CssTree.walk(ast, (function (node) {
        if (node.type === "Atrule") {
          console.log(AnimatedComponent.generateAnimatedComponent(CssTree.generate(node.block), "NameOne"));
          return ;
        }
        
      }));

exports.ast = ast;
/* ast Not a pure module */
